; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
;	Please visit documentation for the other options and examples
;	https://docs.platformio.org/page/projectconf.html
;	https://docs.platformio.org/page/faq/index.html

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
build_flags = 
	; Suppress portability warnings from MD_MAX72XX
	-Wno-expansion-to-defined
	; ESP32Async/AsyncTCP recommends to use a smaller TCP stack size: default of 16k is far too much
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
	; Next line enables ESP-IDF logging, instead of (more bloated) Arduino based logging
	-D USE_ESP_IDF_LOG=1
  	-D CONFIG_LOG_COLORS=1
	; Maximum log level for whole application (can be overruled for src files with LOG_LOCAL_LEVEL in build_src_flags)
	-D CORE_DEBUG_LEVEL=ESP_LOG_INFO

; Extend the default build flags (also for used libs) with additional flags for the src directory only
build_src_flags =
	-Og
	-Wall -Wextra
	-Wno-unused-parameter
    ; Maximum log level for src files, can be higher (or lower, equal) than CORE_DEBUG_LEVEL
	-D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG

upload_protocol = esptool
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, log2file
lib_compat_mode = strict
lib_ldf_mode = chain

lib_deps = 
	ESP32Async/AsyncTCP @ 3.5.0
	ESP32Async/ESPAsyncWebServer @ 3.12.1
	tzapu/WiFiManager @ 2.0.17
	olikraus/U8g2 @ 2.36.18
	SPI
	majicdesigns/MD_MAX72XX@^3.5.1
	majicdesigns/MD_Parola@^3.7.3
	https://github.com/boskieft/neopixel.git

custom_component_remove = 
	espressif/esp_hosted
	espressif/esp_wifi_remote
	espressif/esp-dsp
	espressif/esp32-camera
	espressif/libsodium
	espressif/esp-modbus
	espressif/qrcode
	espressif/esp_insights
	espressif/esp_diag_data_store
	espressif/esp_diagnostics
	espressif/esp_rainmaker
	espressif/rmaker_common

[env:esp32c3]
board = adafruit_qtpy_esp32c3
board_build.partitions = boards/Part_TOT4MB_FS512KB.csv

[env:esp32c6]
board = seeed_xiao_esp32c6

[env:esp32]
board=wemos_d1_mini32

[env:esp32s2]
board=lolin_s2_mini
; 07jul26: CANNOT GET LOGGING TO WORK ON THIS BOARD
; (the board does work with Arduino Core 2 on my Analog clock)
; Tried about all configs I could think of, nothing works in VSC monitor
; Only thing that does work is PuttY terminal and 1x/sec Serial.println("Hello world") in loop()

; Serial Monitor control lines
;monitor_dtr = 1
;monitor_rts = 1

build_flags = 
	-Og
	-Wall -Wextra
	-Wno-unused-parameter
	; ESP32Async/AsyncTCP recommends to use a smaller TCP stack size: default of 16k is far too much
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
	; Next line enables ESP-IDF logging, instead of (more bloated) Arduino based logging
	-D USE_ESP_IDF_LOG=1
  	-D CONFIG_LOG_COLORS=1

[env:esp32s3]
board = lilygo-t3-s3
build_flags = 
	${env.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
